In [117]:
import pathlib

import pandas as pd

from transit import cleaning

In [2]:
project_root = pathlib.Path('../..')
project_root.resolve()

PosixPath('/home/jnban/projects/roanoke-transit')

In [3]:
path_output = project_root / 'web/va/roanoke/metroflex'
path_output.mkdir(exist_ok=True, parents=True)
path_output.resolve()

PosixPath('/home/jnban/projects/roanoke-transit/web/va/roanoke/metroflex')

In [8]:
src_df = pd.read_excel(
    project_root / 'data/metroflex/Copy of FEBRUARY 2025 METRO FLX TRIP REPORT.xls',
    sheet_name='Sheet1',
    header=2
)
src_df

,Customer,Customer Summary,Trip Date,Pickup Address,Dropoff Address,Miles,Pickup Address.1,Dropoff Address.1,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15,Unnamed: 16,Unnamed: 17
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2025-02-04 22:54:16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,No show,Yes,ROSS/ CITI TRENDS,apts.,Guests,0.0,"1415 Towne Square Blvd\nRoanoke, VA 24012","1720 Grandin Rd Sw\nRoanoke, VA 24018",NaN,0.0,NaN,NaN,Attendants,0.0,NaN,NaN,NaN,NaN
3,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3896,No show,No,CEI -- ROANOKE,NaN,Guests,0.0,"4411 Plantation Rd Ne\nRoanoke, VA 24019","1321 Leon St Nw\nRoanoke, VA 24017",NaN,0.0,NaN,NaN,Attendants,0.0,NaN,NaN,NaN,NaN
3897,2025-02-14 23:00:44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3898,No show,No,CEI -- ROANOKE,NaN,Guests,0.0,"4411 Plantation Rd Ne\nRoanoke, VA 24019","1321 Leon St Nw\nRoanoke, VA 24017",NaN,0.0,NaN,NaN,Attendants,0.0,NaN,NaN,NaN,NaN
3899,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3900,Page -1 of 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [119]:
df = cleaning.drop_empty_rows(src_df)
df.drop(df.index[-1], inplace=True) # drop last row
df.rename(columns={'Trip Date': 'Pickup Address Details'}, inplace=True)

df = cleaning.downshift_alternating_values(df, column='Customer', target='Trip Date', increment=2)
df = cleaning.drop_empty_rows(df)

df.drop([
    'Customer',
    'Dropoff Address',
    'Unnamed: 8',
    'Unnamed: 9',
    'Unnamed: 10',
    'Unnamed: 11',
    'Unnamed: 12',
    'Unnamed: 14',
    'Unnamed: 15',
    'Unnamed: 16',
    'Unnamed: 17',
], axis=1, inplace=True)

df.rename(columns={
    'Customer Summary': 'No show',
    'Unnamed: 13': 'Attendants',
    'Pickup Address': 'Dropoff Address Details',
    'Pickup Address.1': 'Pickup Address',
    'Dropoff Address.1': 'Dropoff Address',
}, inplace=True)

df.to_csv(project_root / 'data/metroflex/metroflex-2025-02-trip-report-cleaned.csv')
df

,No show,Pickup Address Details,Dropoff Address Details,Miles,Pickup Address,Dropoff Address,Attendants,Trip Date
2,Yes,ROSS/ CITI TRENDS,apts.,0.0,"1415 Towne Square Blvd\nRoanoke, VA 24012","1720 Grandin Rd Sw\nRoanoke, VA 24018",0.0,2025-02-04 22:54:16
6,No,VA WESTERN/ MCFARLAND CENTER (RIGHT SIDE FROM ...,NaN,0.0,"3094 Colonial Ave Sw\nRoanoke, VA 24015","1306 Carroll Ave Nw\nRoanoke, VA 24017",0.0,2025-01-28 21:21:17
8,No,VA WESTERN/ MCFARLAND CENTER (RIGHT SIDE FROM ...,NaN,0.0,"3094 Colonial Ave Sw\nRoanoke, VA 24015","1306 Carroll Ave Nw\nRoanoke, VA 24017",0.0,2025-02-03 22:05:34
10,No,VA WESTERN/ MCFARLAND CENTER (RIGHT SIDE FROM ...,NaN,0.0,"3094 Colonial Ave Sw\nRoanoke, VA 24015","1306 Carroll Ave Nw\nRoanoke, VA 24017",0.0,2025-02-04 21:38:53
12,No,VA WESTERN/ MCFARLAND CENTER (RIGHT SIDE FROM ...,NaN,0.0,"3094 Colonial Ave Sw\nRoanoke, VA 24015","1306 Carroll Ave Nw\nRoanoke, VA 24017",0.0,2025-02-17 22:42:00
...,...,...,...,...,...,...,...,...
3890,No,CEI -- ROANOKE,NaN,0.0,"4411 Plantation Rd Ne\nRoanoke, VA 24019","1321 Leon St Nw\nRoanoke, VA 24017",0.0,2025-01-31 22:49:07
3892,No,CEI -- ROANOKE,NaN,0.0,"4411 Plantation Rd Ne\nRoanoke, VA 24019","1321 Leon St Nw\nRoanoke, VA 24017",0.0,2025-02-05 22:59:48
3894,Yes,CEI -- ROANOKE,NaN,0.0,"4411 Plantation Rd Ne\nRoanoke, VA 24019","1321 Leon St Nw\nRoanoke, VA 24017",0.0,2025-02-12 23:00:00
3896,No,CEI -- ROANOKE,NaN,0.0,"4411 Plantation Rd Ne\nRoanoke, VA 24019","1321 Leon St Nw\nRoanoke, VA 24017",0.0,2025-02-13 23:12:26
3898,No,CEI -- ROANOKE,NaN,0.0,"4411 Plantation Rd Ne\nRoanoke, VA 24019","1321 Leon St Nw\nRoanoke, VA 24017",0.0,2025-02-14 23:00:44